project:
  type: website

website:
  title: "La connaissance à l'OFB en Île-de-France"
  navbar:
    left:
      - index.qmd
      - productions.qmd
    logo: logo.png
  favicon: favicon.png

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-title: "Menu"
    toc-depth: 2

editor: visual

knit:
  cache: true
