project:
  type: website

website:
  title: "La connaissance à l'OFB en Île-de-France"
  navbar:
    left:
      - productions.qmd
    logo: logo.png
    favicon: favicon.png

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

knit:
  cache: true
