---
title: "Productions"
header-includes:
  - <script data-goatcounter="https://ofb-idf.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
---

## Productions régionales

### Tableaux de bord

-   [Suivis hydrobiologiques en Île-de-France](https://ofbidf.shinyapps.io/HydrobioIdF/){target="'_blank'"}
-   [Suivi des étiages (ONDE) en Île-de-France](https://ofb-idf.github.io/PRR_ONDE/){target="'_blank'"}
-   [Faune protégée d'Île-de-France](https://ofbidf.shinyapps.io/EspecesProtegeesIDF/){target="'_blank'"}

### Livrets

-   [Etude du chat forestier en Île-de-France](https://oai-gem.ofb.fr/exl-php/document-affiche/ofb_recherche_oai/OUVRE_DOC/49974?fic=doc00073302.pdf){target="'_blank'"}

### Parlons de connaissance

-   [Un félin sauvage en Île-de-France ? Le retour du chat forestier](https://www.youtube.com/watch?v=UopppCJfUHA){target="_blank"} (MNHN-OFB, 2024)
-   [Sur les traces du chat forestier en Île-de-France](https://www.youtube.com/watch?v=0P0JTVxUEBA&t=7670s){target="_blank"} (Rencontres naturalistes ARB, 2022)
-   [Le retour du Castor en Île-de-France](https://www.radiofrance.fr/franceculture/podcasts/la-science-au-labo/le-retour-du-castor-en-ile-de-france-8018346){target="'_blank'"} (Reportage terrain, France Culture, 2025)
-   [Castor, les dents de la rivière](https://www.facebook.com/Montauger/videos/castor-les-dents-de-la-rivière/2857221884547378/){target="_blank"} (conférence Domaine de Montauger, ENS 91, 2021)

## Contributions à des productions régionales

-   [Liste rouge régionale des poissons d'Île-de-France](https://www.arb-idf.fr/fileadmin/DataStorageKit/ARB/Articles/fichiers/Rencontres_naturalistes_2023/02_Presentation_resultats_LRR_Poissons.pdf){target="_blank"} (ARB, à venir)
-   [Restaurer les continuités écologiques en Île-de-France](https://www.institutparisregion.fr/nos-travaux/publications/restaurer-les-continuites-ecologiques-en-ile-de-france/){target="_blank"} (IPR, 2021)

## Contributions à des productions nationales

-   [Visualisation des données de pêche à l'électricité issues de Aspe](https://ofbidf.shinyapps.io/AspeDashboard/){target="'_blank'"}

