---
title: "Ressources"
---

## Ressources OFB

-   [Panorama des ressources internet](www/Repertoire%20ressources%20internet_2020.pdf){target="_blank"}
-   [Portail applicatif de l'OFB (intranet)](https://intranet.ofb.fr/repertoire-des-applications-et-ressources-pour-la-connaissance){target="_blank"}
-   [Les cartes de répartition d'espèces (Carmen)](https://professionnels.ofb.fr/fr/node/1089){target="_blank"}
-   [Les centres de ressources](https://professionnels.ofb.fr/fr/node/137){target="_blank"}
-   [Le réseau de sites de démonstration (restauration hydromorphologique de cours d'eau)](https://professionnels.ofb.fr/node/358){target="_blank"}
-   [La toile Eaufrance](https://www.eaufrance.fr/sites/default/files/Infographie_dynamique_EF.pdf){target="_blank"}
-   [L'Observatoire national de la biodiversité](https://naturefrance.fr){target="_blank"}

### Patrinat

-   [Le site de Patrinat](http://www.patrinat.fr/fr){target="_blank"}
-   [Tableau des experts naturalistes](www/experts.html){target="_blank"}

## En Île-de-France

### Les outils régionaux

-   [Géonat'IdF](https://geonature.arb-idf.fr/geonature/#/){target="_blank"} (plateforme régionale du SINP)
-   [Atlas dynamique de la biodiversité en Île-de-France](https://geonature.arb-idf.fr/atlas){target="_blank"}
-   [Lobelia (outil CBN)](https://lobelia-cbn.fr/consulter/carte){target="_blank"}
-   [Géo-Seine-Normandie, le portail de la gestion de l'eau](https://geo.eau-seine-normandie.fr/#/home/MESU){target="_blank"}

### Les partenaires régionaux

-   [L'Agence Régionale de la Biodiversité Île-de-France](https://www.arb-idf.fr){target="_blank"}
-   [Le Conservatoire Botanique National du Bassin Parisien](https://cbnbp.mnhn.fr/cbnbp/index.jsp){target="_blank"}
-   [L'Agence de l'eau Seine Normandie](https://www.eau-seine-normandie.fr){target="_blank"}

## Autres ressources

-   [INPN OpenObs](https://openobs.mnhn.fr){target="_blank"}: Portail français d'accès aux données d'observation sur les espèces

