project:
  type: website

website:
  title: "La connaissance à l'OFB"
  navbar:
    left:
      - index.qmd
      - calendrier.qmd
      - productions.qmd
      - ressources.qmd
    logo: www/logo.png
  favicon: www/favicon.png

format:
  html:
    theme: litera
    css: www/styles.css
    toc: true
    toc-title: "Menu"
    toc-depth: 2

knit:
  cache: true
